### ISSUE TITLE
Newer builds of archipelago do not allow options to be called "random"

### ISSUE THREAD

**Issue by TreZc0** [toontown-archipelago/toontown-archipelago#143]
Hey there :)
Latest master of archipelago rejects options that are called "random", and sadly, StartingTaskOption does boost one option called "random".

Would it be okay for you to rename the "random" option of StartingTaskOption to "randomized"?

Renaming it to "option_randomized" like many other games do would also solve the small incompatibility issue there :)

**Comment by PIEisFANTASTIC** [comment]
Fixed for a future update
