### ISSUE TITLE
Game Crash when closing Discord with the Discord Rich Presence option enabled

### ISSUE THREAD

**Issue by ahy8956** [toontown-archipelago/toontown-archipelago#174]
currently on ttap release version 0.12.2, along with latest discord PTB client on windows 10

to reproduce:
-turn on discord rich presence in the shticker book options
-wait for discord to show the game under rich presence
-close discord
the game then crashes.

example log:
[archipelago-241101_211341.log](https://github.com/user-attachments/files/17605522/archipelago-241101_211341.log)

**Comment by DarthMDev** [comment]
Ill see what i can do
