### ISSUE TITLE
Skip cutscene button for bosses

### ISSUE THREAD

**Issue by DevvyDont** [toontown-archipelago/toontown-archipelago#8]
Similarly to clash, add a skip cutscene button for boss cutscenes. This should work for the following cutscenes:

- VP Intro
- VP Pre skelecog round
- CFO Intro
- CFO Craning tutorial
- CJ Intro
- CJ Pre cannon round
- CEO Pre waiter round
- CEO Pre feeding round 
- CEO Pre second cog round (optional, cutscene is very short)
- CEO Pre boss fight (optional, cutscene is very short)

**Comment by DarthMDev** [comment]
I have done this before for a previous server I worked on so i can start on this

**Comment by DarthMDev** [comment]
Do we want first time player checks or just be able to skip regardless with majority vote?
